/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as DossierRouteImport } from './routes/dossier'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as IntelRouteImport } from './routes/intel'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as TraceRouteImport } from './routes/trace'
import { Route as VaspsRouteImport } from './routes/vasps'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const DossierRoute = DossierRouteImport.update({
  id: '/dossier',
  path: '/dossier',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelRoute = IntelRouteImport.update({
  id: '/intel',
  path: '/intel',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const TraceRoute = TraceRouteImport.update({
  id: '/trace',
  path: '/trace',
  getParentRoute: () => rootRouteImport,
} as any)
const VaspsRoute = VaspsRouteImport.update({
  id: '/vasps',
  path: '/vasps',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/dossier': typeof DossierRoute
  '/evidence': typeof EvidenceRoute
  '/intel': typeof IntelRoute
  '/playbook': typeof PlaybookRoute
  '/trace': typeof TraceRoute
  '/vasps': typeof VaspsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/dossier': typeof DossierRoute
  '/evidence': typeof EvidenceRoute
  '/intel': typeof IntelRoute
  '/playbook': typeof PlaybookRoute
  '/trace': typeof TraceRoute
  '/vasps': typeof VaspsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/dossier': typeof DossierRoute
  '/evidence': typeof EvidenceRoute
  '/intel': typeof IntelRoute
  '/playbook': typeof PlaybookRoute
  '/trace': typeof TraceRoute
  '/vasps': typeof VaspsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cases'
    | '/dossier'
    | '/evidence'
    | '/intel'
    | '/playbook'
    | '/trace'
    | '/vasps'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cases'
    | '/dossier'
    | '/evidence'
    | '/intel'
    | '/playbook'
    | '/trace'
    | '/vasps'
  id:
    | '__root__'
    | '/'
    | '/cases'
    | '/dossier'
    | '/evidence'
    | '/intel'
    | '/playbook'
    | '/trace'
    | '/vasps'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesRoute: typeof CasesRoute
  DossierRoute: typeof DossierRoute
  EvidenceRoute: typeof EvidenceRoute
  IntelRoute: typeof IntelRoute
  PlaybookRoute: typeof PlaybookRoute
  TraceRoute: typeof TraceRoute
  VaspsRoute: typeof VaspsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossier': {
      id: '/dossier'
      path: '/dossier'
      fullPath: '/dossier'
      preLoaderRoute: typeof DossierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intel': {
      id: '/intel'
      path: '/intel'
      fullPath: '/intel'
      preLoaderRoute: typeof IntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trace': {
      id: '/trace'
      path: '/trace'
      fullPath: '/trace'
      preLoaderRoute: typeof TraceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vasps': {
      id: '/vasps'
      path: '/vasps'
      fullPath: '/vasps'
      preLoaderRoute: typeof VaspsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesRoute: CasesRoute,
  DossierRoute: DossierRoute,
  EvidenceRoute: EvidenceRoute,
  IntelRoute: IntelRoute,
  PlaybookRoute: PlaybookRoute,
  TraceRoute: TraceRoute,
  VaspsRoute: VaspsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
