import { inr, usdt } from "./format";
import { KNOWN_VASPS } from "./registry";
import type { Endpoint } from "./types";

export function noticeId(complaintId: string, wallet: string): string {
  const seed = `${complaintId}:${wallet}`.replace(/[^A-Za-z0-9]/g, "").slice(-10).toUpperCase();
  return `GARUDA-FZ-${seed}`;
}

export function freezeNoticeEn(opts: {
  officerId: string;
  complaintId: string;
  sourceWallet: string;
  endpoint: Endpoint;
}): string {
  const v = KNOWN_VASPS[opts.endpoint.wallet];
  const id = noticeId(opts.complaintId, opts.endpoint.wallet);
  return [
    "INDIAN CYBER CRIME COORDINATION CENTRE (I4C)",
    "Ministry of Home Affairs — CIS Division",
    "SAHYOG / Emergency Asset Preservation Request",
    "",
    `Notice ID: ${id}`,
    `Date: ${new Date().toLocaleString("en-IN", { timeZone: "Asia/Kolkata" })} IST`,
    `From: ${opts.officerId}`,
    `To: ${v?.nodal ?? "Nodal Officer"}, ${opts.endpoint.entity}`,
    `Channel: ${v?.contact ?? "registered nodal desk"}`,
    "",
    `Subject: Immediate freeze of crypto assets linked to NCRP ${opts.complaintId}`,
    "",
    "Legal basis",
    "1. Section 91, Code of Criminal Procedure, 1973 — production and preservation of documents/electronic records.",
    "2. Section 17, Prevention of Money Laundering Act, 2002 — attachment and freeze of proceeds of crime.",
    "3. Information Technology Act, 2000 — duty to preserve digital evidence and subscriber information.",
    "4. I4C / MHA advisory on crypto-asset tracing for law-enforcement agencies.",
    "",
    "Facts (machine-traced, officer-verified)",
    `A victim-reported wallet ${opts.sourceWallet} was walked by the GARUDA attribution engine.`,
    `Endpoint cluster ${opts.endpoint.wallet} is attributed to ${opts.endpoint.entity}.`,
    `Value observed at this sink: ${usdt(opts.endpoint.amountUsdt)} (≈ ${inr(opts.endpoint.amountUsdt)}).`,
    `Hop distance from the reported wallet: ${opts.endpoint.hops}. Risk score: ${opts.endpoint.risk}/100.`,
    "",
    "You are requested to IMMEDIATELY, and in any event within four (4) hours of receipt:",
    "a) Freeze crypto balances and linked INR / bank / UPI rails for this cluster and any co-attributed deposit addresses;",
    "b) Preserve KYC, CKYC, video-KYC, login IPs, device fingerprints, order books, and internal transfer logs for 180 days;",
    "c) Restrict withdrawals, P2P completion, and internal shuttling for a minimum of 72 hours;",
    "d) Acknowledge this notice to the requesting officer with a freeze confirmation number.",
    "",
    "Non-preservation of these records after notice may attract consequences under PMLA and the IT Act.",
    "",
    "This notice is generated by GARUDA for I4C investigative use. It is a draft statutory communication — serve through SAHYOG / the registered nodal channel.",
  ].join("\n");
}

export function freezeNoticeHi(opts: {
  officerId: string;
  complaintId: string;
  sourceWallet: string;
  endpoint: Endpoint;
}): string {
  const v = KNOWN_VASPS[opts.endpoint.wallet];
  const id = noticeId(opts.complaintId, opts.endpoint.wallet);
  return [
    "भारतीय साइबर अपराध समन्वय केंद्र (I4C)",
    "गृह मंत्रालय — सीआईएस प्रभाग",
    "सहयोग / आपात परिसंपत्ति संरक्षण अनुरोध",
    "",
    `नोटिस संख्या: ${id}`,
    `दिनांक: ${new Date().toLocaleString("hi-IN", { timeZone: "Asia/Kolkata" })} IST`,
    `प्रेषक: ${opts.officerId}`,
    `सेवा में: ${v?.nodal ?? "नोडल अधिकारी"}, ${opts.endpoint.entity}`,
    `माध्यम: ${v?.contact ?? "पंजीकृत नोडल डेस्क"}`,
    "",
    `विषय: एनसीआरपी ${opts.complaintId} से जुड़ी क्रिप्टो परिसंपत्तियों का तत्काल अवरोधन`,
    "",
    "कानूनी आधार",
    "1. दंड प्रक्रिया संहिता, 1973 की धारा 91 — दस्तावेज / इलेक्ट्रॉनिक अभिलेख प्रस्तुत करना व सुरक्षित रखना।",
    "2. धन शोधन निवारण अधिनियम, 2002 की धारा 17 — अपराध की आय का कुर्क / फ्रीज।",
    "3. सूचना प्रौद्योगिकी अधिनियम, 2000 — डिजिटल साक्ष्य व ग्राहक सूचना संरक्षित रखने का कर्तव्य।",
    "4. विधि-प्रवर्तन हेतु क्रिप्टो-परिसंपत्ति अनुरेखण पर आई4सी / गृह मंत्रालय सलाह।",
    "",
    "तथ्य (इंजन-ट्रेस, अधिकारी-सत्यापित)",
    `पीड़ित द्वारा सूचित वॉलेट ${opts.sourceWallet} का GARUDA इंजन द्वारा अनुरेखण किया गया।`,
    `अंतिम क्लस्टर ${opts.endpoint.wallet} ${opts.endpoint.entity} से आरोपित है।`,
    `इस पड़ाव पर मूल्य: ${usdt(opts.endpoint.amountUsdt)} (लगभग ${inr(opts.endpoint.amountUsdt)})।`,
    `रिपोर्टेड वॉलेट से दूरी: ${opts.endpoint.hops} hop. जोखिम अंक: ${opts.endpoint.risk}/100.`,
    "",
    "आपसे अनुरोध है कि प्राप्ति के चार (4) घंटे के भीतर:",
    "क) इस क्लस्टर व सह-आरोपित जमा पतों के क्रिप्टो शेष तथा जुड़े INR / बैंक / यूपीआई रास्ते फ्रीज करें;",
    "ख) केवाईसी, लॉगिन आईपी, डिवाइस फिंगरप्रिंट, ऑर्डर बुक व आंतरिक ट्रांसफर लॉग 180 दिनों तक सुरक्षित रखें;",
    "ग) निकासी, पी2पी पूर्णता व आंतरिक स्थानांतरण न्यूनतम 72 घंटे रोकें;",
    "घ) फ्रीज पुष्टि संख्या के साथ इस अधिकारी को पावती भेजें।",
    "",
    "नोटिस के बाद अभिलेख न रखना पीएमएलए व आईटी अधिनियम के अंतर्गत परिणामी हो सकता है।",
    "",
    "यह नोटिस GARUDA द्वारा आई4सी जाँच हेतु तैयार मसौदा है — सहयोग / पंजीकृत नोडल माध्यम से तामील करें।",
  ].join("\n");
}
