import { inr, usdt } from "./format";
import { KNOWN_VASPS } from "./registry";
import type { Endpoint } from "./types";

export function noticeId(complaintId: string, wallet: string): string {
  const seed = `${complaintId}:${wallet}`.replace(/[^A-Za-z0-9]/g, "").slice(-10).toUpperCase();
  return `GARUDA-FZ-${seed}`;
}

/**
 * SAHYOG-style emergency asset preservation draft (English).
 * Officer must review, sign, and transmit via official nodal / SAHYOG channel.
 */
export function freezeNoticeEn(opts: {
  officerId: string;
  complaintId: string;
  sourceWallet: string;
  endpoint: Endpoint;
  station?: string;
}): string {
  const v = KNOWN_VASPS[opts.endpoint.wallet];
  const id = noticeId(opts.complaintId, opts.endpoint.wallet);
  const sla = v?.freezeSlaHours ?? 6;
  const station = opts.station ? ` / ${opts.station}` : "";
  return [
    "INDIAN CYBER CRIME COORDINATION CENTRE (I4C)",
    "Ministry of Home Affairs — CIS Division",
    "SAHYOG / Emergency Asset Preservation Request",
    "",
    `Notice ID: ${id}`,
    `Date: ${new Date().toLocaleString("en-IN", { timeZone: "Asia/Kolkata" })} IST`,
    `From: ${opts.officerId}${station}`,
    `To: ${v?.nodal ?? "Nodal Officer"}, ${opts.endpoint.entity}`,
    `Channel: ${v?.contact ?? "registered nodal desk"}`,
    `Reference SLA (exchange-published): ${sla} hour(s)`,
    "",
    `Subject: Immediate freeze of crypto assets linked to NCRP ${opts.complaintId}`,
    "",
    "Legal basis",
    "1. Section 91, Code of Criminal Procedure, 1973 — production and preservation of documents and electronic records.",
    "2. Section 17, Prevention of Money Laundering Act, 2002 — attachment and freeze of proceeds of crime.",
    "3. Information Technology Act, 2000 — duty to preserve digital evidence and subscriber information.",
    "4. Applicable I4C / MHA advisories on crypto-asset tracing for law-enforcement agencies.",
    "",
    "Facts (machine-traced; to be officer-verified before service)",
    `A victim-reported wallet ${opts.sourceWallet} was walked by the GARUDA attribution engine.`,
    `Endpoint cluster / deposit address ${opts.endpoint.wallet} is attributed to ${opts.endpoint.entity} (${opts.endpoint.kind}).`,
    `Value observed at this sink: ${usdt(opts.endpoint.amountUsdt)} (≈ ${inr(opts.endpoint.amountUsdt)}).`,
    `Hop distance from the reported wallet: ${opts.endpoint.hops}. Risk score: ${opts.endpoint.risk}/100.`,
    `Recoverable flag (Indian VASP / rails): ${opts.endpoint.recoverable ? "YES — priority freeze target" : "NO — still preserve records"}.`,
    "",
    "You are requested to act IMMEDIATELY, and in any event within four (4) hours of receipt:",
    "a) Freeze crypto balances held against this cluster and any co-attributed deposit addresses, and freeze linked INR / bank / UPI rails where under your control;",
    "b) Preserve KYC, CKYC, video-KYC, registered mobile / email, login IPs, device fingerprints, order books, deposit tags, and internal transfer logs for a minimum of 180 days;",
    "c) Restrict withdrawals, P2P completion, internal shuttling, and off-platform transfers for a minimum of 72 hours or until written release by the requesting authority;",
    "d) Acknowledge this notice in writing with a freeze confirmation reference to the requesting officer.",
    "",
    "Failure to preserve records after receipt of this notice may attract consequences under the PMLA and the IT Act.",
    "",
    "Disclaimer: This document is a draft statutory communication generated by GARUDA for I4C investigative use.",
    "It must be reviewed and signed by an authorised officer and served only through SAHYOG or the registered nodal channel of the VASP.",
    "It does not by itself constitute a court order or FIU-IND direction.",
  ].join("\n");
}

export function freezeNoticeHi(opts: {
  officerId: string;
  complaintId: string;
  sourceWallet: string;
  endpoint: Endpoint;
  station?: string;
}): string {
  const v = KNOWN_VASPS[opts.endpoint.wallet];
  const id = noticeId(opts.complaintId, opts.endpoint.wallet);
  const station = opts.station ? ` / ${opts.station}` : "";
  return [
    "भारतीय साइबर अपराध समन्वय केंद्र (I4C)",
    "गृह मंत्रालय — सीआईएस प्रभाग",
    "सहयोग / आपात परिसंपत्ति संरक्षण अनुरोध",
    "",
    `नोटिस संख्या: ${id}`,
    `दिनांक: ${new Date().toLocaleString("hi-IN", { timeZone: "Asia/Kolkata" })} IST`,
    `प्रेषक: ${opts.officerId}${station}`,
    `सेवा में: ${v?.nodal ?? "नोडल अधिकारी"}, ${opts.endpoint.entity}`,
    `माध्यम: ${v?.contact ?? "पंजीकृत नोडल डेस्क"}`,
    "",
    `विषय: एनसीआरपी ${opts.complaintId} से जुड़ी क्रिप्टो परिसंपत्तियों का तत्काल अवरोधन`,
    "",
    "कानूनी आधार",
    "1. दंड प्रक्रिया संहिता, 1973 की धारा 91 — दस्तावेज / इलेक्ट्रॉनिक अभिलेख प्रस्तुत करना व सुरक्षित रखना।",
    "2. धन शोधन निवारण अधिनियम, 2002 की धारा 17 — अपराध की आय का कुर्क / फ्रीज।",
    "3. सूचना प्रौद्योगिकी अधिनियम, 2000 — डिजिटल साक्ष्य व ग्राहक सूचना संरक्षित रखने का कर्तव्य।",
    "4. विधि-प्रवर्तन हेतु क्रिप्टो-परिसंपत्ति अनुरेखण पर आई4सी / गृह मंत्रालय सलाह।",
    "",
    "तथ्य (इंजन-ट्रेस; तामील से पहले अधिकारी-सत्यापित करें)",
    `पीड़ित द्वारा सूचित वॉलेट ${opts.sourceWallet} का GARUDA इंजन द्वारा अनुरेखण किया गया।`,
    `अंतिम क्लस्टर / जमा पता ${opts.endpoint.wallet} ${opts.endpoint.entity} (${opts.endpoint.kind}) से आरोपित है।`,
    `इस पड़ाव पर मूल्य: ${usdt(opts.endpoint.amountUsdt)} (लगभग ${inr(opts.endpoint.amountUsdt)})।`,
    `रिपोर्टेड वॉलेट से दूरी: ${opts.endpoint.hops} hop. जोखिम अंक: ${opts.endpoint.risk}/100.`,
    `भारतीय VASP / रेल पर वसूली संभव: ${opts.endpoint.recoverable ? "हाँ — प्राथमिक फ्रीज लक्ष्य" : "नहीं — फिर भी अभिलेख सुरक्षित रखें"}।`,
    "",
    "आपसे अनुरोध है कि प्राप्ति के चार (4) घंटे के भीतर:",
    "क) इस क्लस्टर व सह-आरोपित जमा पतों के क्रिप्टो शेष तथा नियंत्रण में आने वाले INR / बैंक / यूपीआई रास्ते फ्रीज करें;",
    "ख) केवाईसी, वीडियो-केवाईसी, पंजीकृत मोबाइल / ईमेल, लॉगिन आईपी, डिवाइस फिंगरप्रिंट, ऑर्डर बुक व आंतरिक ट्रांसफर लॉग न्यूनतम 180 दिनों तक सुरक्षित रखें;",
    "ग) निकासी, पी2पी पूर्णता, आंतरिक स्थानांतरण व ऑफ-प्लेटफॉर्म ट्रांसफर न्यूनतम 72 घंटे या प्राधिकारी की लिखित अनुमति तक रोकें;",
    "घ) फ्रीज पुष्टि संदर्भ संख्या के साथ इस अधिकारी को लिखित पावती भेजें।",
    "",
    "नोटिस प्राप्ति के बाद अभिलेख न रखना पीएमएलए व आईटी अधिनियम के अंतर्गत परिणामी हो सकता है।",
    "",
    "अस्वीकरण: यह दस्तावेज GARUDA द्वारा आई4सी जाँच हेतु तैयार मसौदा है।",
    "इसे प्राधिकृत अधिकारी द्वारा समीक्षा व हस्ताक्षर के बाद ही सहयोग / पंजीकृत नोडल माध्यम से तामील करें।",
    "यह स्वयं न्यायालय आदेश या FIU-IND निर्देश नहीं है।",
  ].join("\n");
}
