import { createFileRoute, Link } from "@tanstack/react-router";
import { Button } from "@/components/ui/button";
import { inr, usdt } from "@/lib/garuda/format";
import { useGaruda } from "@/lib/garuda/store";

export const Route = createFileRoute("/dossier")({ component: DossierPage });

function DossierPage() {
  const trace = useGaruda((s) => s.lastTrace);
  const officerId = useGaruda((s) => s.officerId);

  if (!trace) {
    return (
      <div className="mx-auto max-w-xl py-16 text-center">
        <p className="text-sm text-muted">No trace in session. Run attribution first.</p>
        <Button asChild className="mt-4">
          <Link to="/trace">Open tracer</Link>
        </Button>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-3xl">
      <div className="no-print mb-4 flex gap-2">
        <Button onClick={() => window.print()}>Print / save PDF</Button>
        <Button asChild variant="secondary">
          <Link to="/trace">Back to trace</Link>
        </Button>
      </div>
      <article className="paper-doc rounded-lg p-8 md:p-10">
        <p className="text-xs tracking-[0.18em] uppercase">Indian Cyber Crime Coordination Centre · CIS</p>
        <h1 className="mt-2 font-serif text-3xl">GARUDA forensic dossier</h1>
        <p className="mt-1 text-sm">
          Officer {officerId} · Case {trace.caseId ?? "unattached"} · {new Date(trace.ranAt).toLocaleString("en-IN")} IST
        </p>
        <h2 className="mt-8 font-serif text-xl">1. Target</h2>
        <p className="mt-2 font-mono text-sm">{trace.source}</p>
        <p className="mt-2 text-sm">
          Walked {trace.nodes.length} wallets, {trace.maxHop} hops, {trace.mode} ledger. Recoverable at Indian VASPs:{" "}
          {usdt(trace.recoverableUsdt)} ({inr(trace.recoverableUsdt)}). Mixer-bound: {usdt(trace.lostUsdt)}.
        </p>
        <h2 className="mt-8 font-serif text-xl">2. Endpoints</h2>
        <table className="mt-3 w-full text-left text-sm">
          <thead>
            <tr>
              <th className="pb-1">Entity</th>
              <th>Wallet</th>
              <th>Hops</th>
              <th>Risk</th>
              <th>USDT</th>
            </tr>
          </thead>
          <tbody>
            {trace.endpoints.map((e) => (
              <tr key={e.wallet} className="border-t border-ink/15">
                <td className="py-1.5 pr-2">{e.entity}</td>
                <td className="py-1.5 pr-2 font-mono text-[11px]">{e.wallet}</td>
                <td className="py-1.5 pr-2">{e.hops}</td>
                <td className="py-1.5 pr-2">{e.risk}</td>
                <td className="py-1.5">{e.amountUsdt}</td>
              </tr>
            ))}
          </tbody>
        </table>
        <h2 className="mt-8 font-serif text-xl">3. Typologies</h2>
        {trace.typologies.length ? (
          trace.typologies.map((ty) => (
            <p key={ty.typology} className="mt-2 text-sm">
              <strong>{ty.typology}</strong> at {ty.node}. {ty.description} {ty.officerNote}
            </p>
          ))
        ) : (
          <p className="mt-2 text-sm">No peeling / mixer / bridge pattern above threshold.</p>
        )}
        <h2 className="mt-8 font-serif text-xl">4. Recommended actions</h2>
        <ol className="mt-2 list-decimal space-y-1 pl-5 text-sm">
          {trace.recommendations.map((r) => (
            <li key={r.title}>
              <strong>{r.title}.</strong> {r.detail}
            </li>
          ))}
        </ol>
        <h2 className="mt-8 font-serif text-xl">5. Correlations</h2>
        {trace.correlations.length ? (
          <ul className="mt-2 list-disc pl-5 text-sm">
            {trace.correlations.map((c) => (
              <li key={c.wallet}>
                {c.wallet} · {c.complaintIds.join(", ")}
              </li>
            ))}
          </ul>
        ) : (
          <p className="mt-2 text-sm">No shared wallets with other queued complaints.</p>
        )}
        <p className="mt-10 text-xs">
          Generated by GARUDA for I4C investigative use. Hash-chain the session from the Evidence locker before filing.
        </p>
      </article>
    </div>
  );
}
